### ISSUE TITLE
Index update with ESIndexState can't work with other generic type than String

### ISSUE THREAD

**Issue by pmerienne** [fhussonnois/storm-trident-elasticsearch#5]
There's a dirty cast in the ESIndexState#bulkUpdateIndices line 6 : you're casting generic T to a String!
You should use the serializer to serialize the T instance.

Moreover it could be good to test this state.

**Comment by mnogu** [comment]
:+1:

**Comment by fhussonnois** [comment]
Sorrry I've not had time to work on this. I will fix it as soon as possible.
